// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using njcio_api.Data;

#nullable disable

namespace njcio_api.Migrations
{
    [DbContext(typeof(NjcioContext))]
    [Migration("20260313075046_DiscogsIdNotAutoIncrement")]
    partial class DiscogsIdNotAutoIncrement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("njcio_api.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("njcio_api.Models.AlbumStyle", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StyleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlbumId", "StyleId");

                    b.HasIndex("StyleId");

                    b.ToTable("AlbumStyles");
                });

            modelBuilder.Entity("njcio_api.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("njcio_api.Models.AlbumStyle", b =>
                {
                    b.HasOne("njcio_api.Models.Album", "Album")
                        .WithMany("AlbumStyles")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("njcio_api.Models.Style", null)
                        .WithMany("AlbumStyles")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("njcio_api.Models.Album", b =>
                {
                    b.Navigation("AlbumStyles");
                });

            modelBuilder.Entity("njcio_api.Models.Style", b =>
                {
                    b.Navigation("AlbumStyles");
                });
#pragma warning restore 612, 618
        }
    }
}
